### PR TITLE
Merge opencog/opencog to singnet/opencog

### PR DESCRIPTION
**Pull request by ngeiswei**

### CODE REVIEW

**Comment by ngeiswei** [comment]
Could a brave soul resolve these conflicts?

**Comment by vsbogd** [comment]
BTW, @ngeiswei , I see very old commits on the top of commits chain in this PR.

**Comment by ngeiswei** [comment]
> BTW, @ngeiswei , I see very old commits on the top of commits chain in this PR.

Which ones exactly? I only see the latest commits from https://github.com/opencog/opencog/commits/master

**Comment by ngeiswei** [comment]
Oh, you're right!

Top was meant as in top of the screen, not top of the chronological history.

Very strange...

**Comment by vsbogd** [comment]
@ngeiswei , conflicts are resolved, hopefully we can merge it

**Comment by ngeiswei** [comment]
I'm a bit scared to merge because of these old commits. I intend to look into this after I'm done with current tasks as it is not urgent for me, let me know if it is for you.

**Comment by vsbogd** [comment]
Well, I would not say it is urgent, but @Necr0X0der asked some functionality which is still in opencog/atomspace. Lets say that if it will be urgent for us I will look at the history issue closer.

**Comment by Necr0x0Der** [comment]
> Well, I would not say it is urgent, but @Necr0x0Der asked some functionality which is still in opencog/atomspace. Lets say that if it will be urgent for us I will look at the history issue closer.

Well, it is not too urgent, but we encountered a bug, which appeared to be fixed in opencog/atomspace, and we have already wasted some time trying to figure this out. I'm not sure that there is nothing else...

**Comment by vsbogd** [comment]
Old commits appeared here because some files were moved to `opencog/opencog` from `opencog/atomspace` including history. For example `AttentionBank.h`. Old commits from `opencog/atomspace` appeared in this history chain consequently.

**Comment by ngeiswei** [comment]
Oh OK, thanks for looking into this @vsbogd. I suppose we can merge then.

**Comment by ngeiswei** [comment]
So if you guys are confident enough about the triple merge (cogutil + atomspace + opencog), feel free to go ahead.

**Comment by vsbogd** [comment]
Only doubt I have is failed atomspace BackwardChainerUTest in last PR to the cogutil https://github.com/opencog/cogutil/runs/74471551 I thought it was fixed in atomspace so I ran it again but I see it still fails. Any way I think I can try to merge cogutil and if atomspace will still fail then revert cogutil/master HEAD.

**Pull request merged**
