### PR TITLE
Merge opencog to singnet

### PR DESCRIPTION
**Pull request by vsbogd**
This PR is part of a bunch:
- opencog/cogutil -> singnet/cogutil (no conflicts) PR https://github.com/singnet/cogutil/pull/19
- opencog/atomspace -> singnet/atomspace (no conflicts) https://github.com/singnet/atomspace/pull/53
- opencog/opencog -> singnet/opencog (conflicts resolved) https://github.com/singnet/opencog/pull/54

### CODE REVIEW

**Comment by vsbogd** [comment]
@ngeiswei , could you please take a look. I see too many commits here but I am not sure about the reason.

**Comment by amebel** [comment]
@vsbogd Unlike atomspace and cogutil, singnet/opencog history has diverged from opencog/opencog. If you take the oldest commit in this pr and grep for it you get the following

on opencog/opencog
``` bash
>> git log --grep="Move parameters to icl-parameters.scm" opencog/master
commit 3ac0bcd2a51f8827147242574c4aafb327c3a1d0
Author: Nil Geisweiller <ngeiswei@gmail.com>
Date:   Mon Aug 13 11:05:43 2018 +0300

    Move parameters to icl-parameters.scm
```
on singnet/opencog
```bash
>> git log --grep="Move parameters to icl-parameters.scm" singnet/master
commit ac396656f114459dc028cd6cd710d595ea2c5b50
Author: Nil Geisweiller <ngeiswei@gmail.com>
Date:   Mon Aug 13 11:05:43 2018 +0300

    Move parameters to icl-parameters.scm

commit 84577d8d90cf7728b141aa8d29580f70cc3ea689
Author: Nil Geisweiller <ngeiswei@gmail.com>
Date:   Mon Aug 13 11:05:43 2018 +0300

    Move parameters to icl-parameters.scm

```

**Comment by vsbogd** [comment]
@AmeBel, thanks for looking into this. I also discussed it with @ngeiswei and I see you have raised https://github.com/opencog/opencog/pull/3394 . Unfortunately I will not have time at nearest week to look at it closer, so I am closing it for now.

**Comment by ngeiswei** [comment]
Thanks to https://github.com/opencog/opencog/pull/3394, `opencog/opencog` and `singnet/opencog` are now almost in sync, however merging `opencog/opencog` into `singnet/opencog` produces lot of redundant commits. I'm not sure what's the best course of actions, either force-pushing opencog on singnet, or maybe do a crazy tedious rebase of singnet onto opencog, etc.

**Comment by amebel** [comment]
I think it is best to create a branch of the present master just in case not all of the commits are not ported to opencog/opencog, and then replace it with opencog/opencog master.

**Comment by ngeiswei** [comment]
That's wise.

**Pull request closed without merging**
