### PR TITLE
Configure circleci

### PR DESCRIPTION
**Pull request by amebel**

### CODE REVIEW

**Comment by ferrouswheel** [comment]
So it looks like you've serialised the builds (i.e. put them all in one job). Have you confirmed that this is faster? Or is there another reason for this? The reason for having multiple jobs is so cogutil and atomspace and any other dependencies can all build at the same time.

If we stick with now having a single job for opencog, why don't we follow the same pattern for atomspace or cogutil?

We don't build link-grammar now.

We now rebuild projects even if they are the same git hash as the last build.

The step that installs opencog is called "Install AtomSpace".

I'm happy to have my work thrown out if it's not suitable or falls short, but I'd at least appreciate an explanation of why.

**Comment by ferrouswheel** [comment]
So after looking at atomspace and cogutil, the pattern of how to split builds up into jobs up seems to be:

- for a repo being built, all dependencies are built/installed as part of the main job.
- for anything that depends on the repo, there is another job to test that each downstream project is not broken

Is this correct for how we'll approach CI builds from now?

I guess this makes sense because each circleci job will shows up as a "check" in a github PR, and it'd be confusing to see cogutil being checked when you are working on opencog. Since cogutil doesn't depend on opencog!

**Comment by amebel** [comment]
> I'm happy to have my work thrown out if it's not suitable or falls short, but I'd at least appreciate an explanation of why.

First it is not being thrown away, it is just moved to cogutil repo with few modifications. But, it was my mistake for not having a description on this pr.

> We don't build link-grammar now.

Link-grammar has had a release process, and we work against the current release. So I don't think we need to test it. Maybe it should be done as part of the docker image repo, when a new version is released?

> We now rebuild projects even if they are the same git hash as the last build.

I don't get why a git hash will be the same as the last build. I guess if a run fails due to circleci bug, or network timeout during clone, or some other random stuff,  then we would have to manually trigger a rebuild, thus having the same hash as the last build. What am I missing?

> Is this correct for how we'll approach CI builds from now?

Yes, the argument you stated is the reason. I was assuming that was clear from the private chats, must have misunderstood or not clearly communicated.

**Comment by ferrouswheel** [comment]
re: git hashes, I meant for build dependencies.

My config file had the set up for checking the git hash of dependencies and caching their checkout and build directory based on that. It would recover ok if there is any network timeout because it still runs the same steps.

But it's fine not to do that if ccache is just as fast.

**Pull request merged**
