### PR TITLE
Merge opencog/opencog to singnet/opencog

### PR DESCRIPTION
**Pull request by ngeiswei**

### CODE REVIEW

**Comment by ngeiswei** [comment]
I noticed the checking gets stuck like that once in a while. @AmeBel, any idea why?

**Comment by ngeiswei** [comment]
I have temporarily disabled checking, as I have no idea how long this blocking is gonna last.

**Comment by amebel** [comment]
@ngeiswei circleci builds a commit only once and opencog/opencog:master build failed thus it is stuck. Don't make direct pull-request from master instead, create a new branch and make a pr from it.

**Comment by ngeiswei** [comment]
OMG! Thank you!

**Pull request merged**
